### ISSUE TITLE
Deployment workflow overwrites the CNAME file (was: Website is down)

### ISSUE THREAD

**Issue by francisdb** [haskellfoundation/error-message-index#351]
![Screenshot_20221020-202903](https://user-images.githubusercontent.com/161305/197029316-13b96d9a-93ae-4d4d-a8b4-8ba41fbe1788.jpg)

**Comment by david-christiansen** [comment]
Thanks! It should be up again, but the root problem isn't solved. I'm taking the liberty of editing the issue title so I remember what's going on.

I think the problem is that setting the custom domain in the repository admin creates a file on the `gh-pages` branch, but we need to set up the deploy workflow to do that itself, because right now it overwrites it with a force-push. This means that after every update, we need to go in and remove then re-add the custom domain, which is not a good way to work.

I'll investigate this tomorrow. In the meantime, I believe @serras set up the current thing and may be able to issue a trivial fix if he gets to it before I do.

Thanks!

**Comment by david-christiansen** [comment]
Relevant documentation: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages

**Comment by david-christiansen** [comment]
Thanks again!

**Comment by francisdb** [comment]
Great effort 👍
